server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.60.52:3306/spider_sdwh?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1800000
      connection-timeout: 30000
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      idle-timeout: 600000
  jpa:
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
logging:
  path: /Users/hezy/tmp/log
  level:
    root: info
info:
  project: wendeng
  application:
    name: marketing-compaign-services